const data = [
  {
    id: 0,
    first_name: 'Lonzo',
    last_name: 'Jacobson',
    gender: 'Other',
    subjects: [],
    highest_degree: '',
    home_city: 'Mumbai',
    home_country: 'India',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 1,
    first_name: 'Marley',
    last_name: 'Bergnaum',
    gender: 'Male',
    subjects: [],
    highest_degree: '',
    home_city: 'Tokyo',
    home_country: 'Japan',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 2,
    first_name: 'Queenie',
    last_name: 'Robel',
    gender: 'Female',
    subjects: [],
    highest_degree: '',
    home_city: 'Sao Paulo',
    home_country: 'Brazil',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 3,
    first_name: 'Jade',
    last_name: 'Barrows',
    gender: 'Male',
    subjects: [],
    highest_degree: '',
    home_city: 'Canberra',
    home_country: 'Austrailia',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 4,
    first_name: 'Jett',
    last_name: 'Boyle',
    gender: 'Female',
    subjects: [],
    highest_degree: '',
    home_city: 'Manama',
    home_country: 'Bahrain',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 5,
    first_name: 'Ronaldo',
    last_name: 'Funk',
    gender: 'Other',
    subjects: [],
    highest_degree: '',
    home_city: 'Bridgetown',
    home_country: 'Barbados',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 6,
    first_name: 'Waldo',
    last_name: 'Schimmel',
    gender: 'Female',
    subjects: [],
    highest_degree: '',
    home_city: 'Algiers',
    home_country: 'Algeria',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 7,
    first_name: 'Frank',
    last_name: 'Okuneva',
    gender: 'Other',
    subjects: [],
    highest_degree: '',
    home_city: 'Angola',
    home_country: 'Luanda',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 8,
    first_name: 'Julio',
    last_name: 'Waelchi',
    gender: 'Female',
    subjects: [],
    highest_degree: '',
    home_city: 'Bulgaria',
    home_country: 'Sofia',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 9,
    first_name: 'Verla',
    last_name: 'Zieme',
    gender: 'Female',
    subjects: [],
    highest_degree: '',
    home_city: 'Cameroon',
    home_country: 'Yaounde',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 10,
    first_name: 'Trisha',
    last_name: 'Nienow',
    gender: 'Female',
    subjects: [],
    highest_degree: '',
    home_city: '',
    home_country: 'Cape Verde',
    home_timezone: 'Praia',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 11,
    first_name: 'Brandt',
    last_name: 'Schroeder',
    gender: 'Female',
    subjects: [],
    highest_degree: '',
    home_city: 'Comoros',
    home_country: 'Moroni',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 12,
    first_name: 'Marco',
    last_name: 'Bogisich',
    gender: 'Other',
    subjects: [],
    highest_degree: '',
    home_city: 'Denmark',
    home_country: 'Copenhagen',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 13,
    first_name: 'Kayley',
    last_name: 'Kautzer',
    gender: 'Male',
    subjects: [],
    highest_degree: '',
    home_city: 'Ecuador',
    home_country: 'Quito',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 14,
    first_name: 'Lon',
    last_name: 'Feest',
    gender: 'Other',
    subjects: [],
    highest_degree: '',
    home_city: 'Paris',
    home_country: 'France',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 15,
    first_name: 'Karlie',
    last_name: 'Nader',
    gender: 'Other',
    subjects: [],
    highest_degree: '',
    home_city: 'Athens',
    home_country: 'Greece',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 16,
    first_name: 'Vernice',
    last_name: 'Torphy',
    gender: 'Female',
    subjects: [],
    highest_degree: '',
    home_city: 'Georgetown',
    home_country: 'Guyana',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 17,
    first_name: 'Carmel',
    last_name: 'Gutmann',
    gender: 'Female',
    subjects: [],
    highest_degree: '',
    home_city: '',
    home_country: '',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 18,
    first_name: 'Cicero',
    last_name: 'Sauer',
    gender: 'Female',
    subjects: [],
    highest_degree: '',
    home_city: 'Tegucigalpa',
    home_country: 'Honduras',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
  {
    id: 19,
    first_name: 'Lacy',
    last_name: 'Hackett',
    gender: 'Male',
    subjects: [],
    highest_degree: '',
    home_city: 'Budapest',
    home_country: 'Hungary',
    home_timezone: '',
    current_classrooms: [],
    phone: '',
    email: '',
    first_language: '',
    other_languages: [],
  },
];

let education = [
  'High School Diploma or GED',
  'No High School',
  'Not Indicated',
  'Professional Certificate',
  'Some College',
  'Some High School',
  'Trade or Craft Certificate',
];
let timezone = [
  'Greenwich Mean Time (GMT)',
  'Universal Coordinated Time (UTC)',
  'European Central Time (ECT)',
  'Eastern European Time	(EET)',
  '(Arabic) Egypt Standard Time (ART)',
  'Eastern African Time (EAT)',
  'Middle East Time (MET)',
  'Near East Time (NET)',
  'Pakistan Lahore Time (PLT)',
  'India Standard Time (IST)',
  'Bangladesh Standard Time (BST)',
  'Vietnam Standard Time (VST)',
  'China Taiwan Time (CTT)',
  'Japan Standard Time (JST)',
  'Australia Central Time (ACT)',
  'Australia Eastern Time (AET)',
  'Solomon Standard Time (SST)',
  'New Zealand Standard Time (NST)',
  'Midway Islands Time (MIT)',
  'Hawaii Standard Time (HST)',
  'Alaska Standard Time (AST)',
  'Pacific Standard Time (PST)',
  'Phoenix Standard Time (PNT)',
  'Mountain Standard Time (MST)',
  'Central Standard Time (CST)',
  'Eastern Standard Time (EST)',
  'Indiana Eastern Standard Time (IET)',
  'Puerto Rico and US Virgin Islands Time	(PRT)',
  'Canada Newfoundland Time (CNT)',
  'Argentina Standard Time (AGT)',
  'Brazil Eastern Time (BET)',
  'Central African Time CAT)',
];
let subject = [
  'Language Arts',
  'Mathematics',
  'Science',
  'Health',
  'Handwriting',
];

let lang = [
  'Albanian',
  'Burmese',
  'Haitian Creole',
  'Karen',
  'Mandarin',
  'Russian',
  'Tigrigna',
  'Amharic',
  'Cantonese',
  'Hebrew',
  'Khmer',
  'Nepali',
  'Somali',
  'Turkish',
  'Armenian',
  'Farsi',
  'Hindi',
  'Korean',
  'Polish',
  'Spanish',
  'Vietnamese',
  'Arabic',
  'French',
  'Hmong',
  'Laotian',
  'Portuguese',
  'Swahili',
  'Bengali',
  'German',
  'Italian',
  'Lithuanian',
  'Punjabi',
  'Tagalog',
  'Bosnian',
  'Greek',
  'Japanese',
  'Malay',
  'Romanian',
  'Thai',
  'American Sign Language',
  'British Sign Language',
];
let res = [];
const real = data.map((item, index) => {
  let newItem = {
    id: item.id,
    first_name: item.first_name,
    last_name: item.last_name,
    gender: item.gender,
    subjects: [subject[index / index + 1 || 2], subject[index / index || 1]],
    highest_degree: education[index + 2 || index - 2],
    home_city: item.home_city,
    home_country: item.home_country,
    current_classrooms: `Classroom ${index}`,
    phone: Math.random().toString().slice(2, 11),
    email: `${item.first_name.toLocaleLowerCase()}@mail.com`,
    first_language: lang[index],
    other_languages: [
      lang[index + 1 || index - 1],
      lang[index + 2 || index - 2],
    ],
  };
  res.push(newItem);
});
console.log(res);
